In [1]:
import torch

# Tensors

Tensor is a multi-dimensional generalization of a matrix, allowing us to have multidimensional arrays of structured data. We can do mathematical operations on them without knowing what each of the dimensions represents semantically.

They can also be simpler structures like vectors.

![Tensors](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

### Tensor operations

### Construction

```python
torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor
```

Constructs a tensor with data.

Parameters:
* data (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.

Keyword arguments:
* dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from data.

* device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.

* requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

* pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.

In [2]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [3]:
torch.tensor([0, 1])

tensor([0, 1])

In [4]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
    dtype=torch.float64,
    device=torch.device('cuda:0'))

tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64)

In [5]:
torch.tensor(3.14159)

tensor(3.1416)

In [6]:
torch.tensor([])

tensor([])

In [7]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
x.requires_grad_(requires_grad=True)
y = torch.tensor([1, 1, 1, 1],dtype=torch.float32,requires_grad=True) # tensor y 
z = x * y
z = z.mean()
z.backward() 
x.grad

tensor([0.2500, 0.2500, 0.2500, 0.2500])

### Concatenation

```python
torch.cat(tensors, dim=0, *, out=None) → Tensor
```

Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.


Parameters:
* tensors (sequence of Tensors) – any python sequence of tensors of the same type. Non-empty tensors provided must have the same shape, except in the cat dimension.

* dim (int, optional) – the dimension over which the tensors are concatenated

Keyword arguments:
* out (Tensor, optional) – the output tensor.

In [8]:
x = torch.randn(2, 3)
x

tensor([[ 0.3933,  0.3489, -0.1641],
        [-1.3551, -0.8775, -0.1454]])

In [9]:
torch.cat((x, x, x), 0)

tensor([[ 0.3933,  0.3489, -0.1641],
        [-1.3551, -0.8775, -0.1454],
        [ 0.3933,  0.3489, -0.1641],
        [-1.3551, -0.8775, -0.1454],
        [ 0.3933,  0.3489, -0.1641],
        [-1.3551, -0.8775, -0.1454]])

In [10]:
a = torch.ones(2,2)
b = torch.zeros(1,2)
torch.cat((a, b))

tensor([[1., 1.],
        [1., 1.],
        [0., 0.]])

### Reshape

```python
torch.reshape(input, shape) → Tensor
```

Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.

Parameters:
* input (Tensor) – the tensor to be reshaped

* shape (tuple of python:ints) – the new shape

In [11]:
a = torch.arange(4.)
a

tensor([0., 1., 2., 3.])

In [12]:
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [13]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

### Unbind

```python
torch.unbind(input, dim=0) → seq
```

Removes a tensor dimension.

Parameters:
* input (Tensor) – the tensor to unbind
* dim (int) – dimension to remove

In [14]:
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [15]:
a, b = torch.unbind(torch.tensor([[1, 2, 3],[3,4,5]]))
a, b

(tensor([1, 2, 3]), tensor([3, 4, 5]))

### Clamp

```python
torch.clamp(input, min=None, max=None, *, out=None) → Tensor
```

Clamps all elements in input into the range [ min, max ]. Letting min_value and max_value be min and max, respectively, this returns:

$ y_i = min(max(x_i, min\_value_i), max\_value_i) $

If min is None, there is no lower bound. Or, if max is None there is no upper bound.

Parameters:
* input (Tensor) – the input tensor.
* min (Number or Tensor, optional) – lower-bound of the range to be clamped to
* max (Number or Tensor, optional) – upper-bound of the range to be clamped to

Keyword arguments:
* out (Tensor, optional) – the output tensor.

In [16]:
a = torch.randn(4)
a

tensor([-0.4108, -1.7801, -0.2086, -0.3729])

In [17]:
torch.clamp(a, min=-0.5, max=0.5)

tensor([-0.4108, -0.5000, -0.2086, -0.3729])

In [18]:
a = torch.randn(5)
b = torch.empty_like(a)
a, b

(tensor([-0.0610, -2.2499,  0.9637, -0.5109, -2.9252]),
 tensor([0., 0., 0., 0., 0.]))

In [19]:
torch.clamp(a, 0.2, 0.6, out=b)
b

tensor([0.2000, 0.2000, 0.6000, 0.2000, 0.2000])